### ISSUE TITLE
Group E: Basic methods and results

### ISSUE THREAD

**Issue by jkhartshorne** [jodeleeuw/219-2021-eyetracking-analysis#19]

**Comment by jkhartshorne** [comment]
There's an error in the final r box:
>  \> attractiveness.curve <- summary.gaze.view %>% filter(roundness_task == FALSE)
>  Error: Problem with `filter()` input `..1`.
> Input `..1` is `roundness_task == FALSE`.
> x object 'roundness_task' not found
> The error occurred in group 1: time.window = 0.

**Comment by raryskin** [comment]
By the way, if you haven't already, check the main manuscript for some of the methods text. I took what Josh's students wrote and edited a bit for clarity and to make the methods descriptions somewhat parallel across all studies.

**Comment by jkhartshorne** [comment]
@jodeleeuw comparing with the original paper, it looks like there was a pretty significant error in choosing the time period for analysis.

> There was a large variance in decision latency across trials, both within and among observers. We chose 1.67 s (50 samples) prior to the decision as the starting point of analysis, as this represents approximately the mean decision latency minus one standard deviation, and thus all sampling points had average values calculated across at least 67% of all trials.

In the replication, this works out to be about 1.8 sec. However, it was chosen to be:

`cutoff.time <- rt.summary$M - rt.summary$SD`

Or about 0.7 sec. 

So basically the period of analysis was less than half as long as it should have been. This also means that there's no missing data across trials. This will change the numerical results substantially, but I don't know yet if it'll affect the conclusions any.
