### ISSUE TITLE
New data collection?

### ISSUE THREAD

**Issue by raryskin** [jodeleeuw/219-2021-eyetracking-analysis#23]
Will we replicate any of the studies in the lab or online and, if so, which ones?

Will we run the posner task?

**Comment by jodeleeuw** [comment]
I think we have a lot of data already, so I'm in favor of being judicious about how much we try to add to this. So I'm trying to think carefully about the value of adding additional data:

**Replication (in-lab)**: Would tell us something about the degree to which technology vs. population/environment matters here. If we find that in-lab samples are similar, it's a simple takeaway. If we find that in-lab samples are better (or worse, I suppose!), then it's more complicated. In that case the most valuable thing would be to know *why* and to try and come up with recommendations that bring online subjects closer to in-lab subjects. I suppose there's also value in knowing whether WebGazer/jsPsych can be used as a substitute for expensive eye tracking in a lab that doesn't have those resources.

**Replication (online)**: I think the value here would be that we could pre-register a variety of decisions that we make during analysis of the first set of data. It would be relatively simple to do this, probably only requiring a day or two of work to collect the data. But the analysis and writing, even with scripts in place, would take at least a week or more I imagine. BTW, we *did* pre-register the first 5 experiments, but those registrations were somewhat naïve about the problems we would encounter with the analysis work. 

**Posner task**: This could serve as a sort of pre-registered implementation of any recommendations that we come up with from analyzing the first 5 experiments. Probably the most work logistically. I'm on the fence about whether it is worth the added time.

**Comment by raryskin** [comment]
Thanks for the clear summary, Josh! Your point about some labs with fewer resources using Webgazer as their main eye-tracking system (instead of hand coding videos which some people still do!) is really great. We should highlight that in the paper. I bet a lot of people won't think of using it that way. 

I'm in favor of in-lab replication and skipping the other two for now. 

Which studies should we replicate? I think maybe one that worked and one that didn't would make for nice comparisons. My proposal would be Altmann & Kamide (something you could run straightforwardly @jkhartshorne ?) and Ryskin et al., which I could run. What do others think? Is that too narrowly focused on language?

And I still think the plan should be to write the paper without these data initially and then add them in later.

**Comment by arieljames** [comment]
Basic clarifying question! Does in-lab replication mean "have Ps (probably undergrads) come into the lab and do the jsPsych/webgazer study online"? 

I think that would be great to plan to run, and I agree that we can work on the paper without that being ready. 

I was not planning to collect in-person data this Fall (covid wariness), but if desired and covid-possible, I can contribute a modest number of participants (smallish subject pool and 0-2 research assistants, tbd).

**Comment by jkhartshorne** [comment]
Yes, that's what I meant.

On August 11, 2021, Sebastian Waz ***@***.***> wrote:
> Basic clarifying question! Does in-lab replication mean "have Ps
> (probably undergrads) come into the lab and do the jsPsych/webgazer
> study online"?
>
> I think that would be great to plan to run, and I agree that we can
> work on the paper without that being ready.
>
> I was not planning to collect in-person data this Fall (covid
> wariness), but if desired and covid-possible, I can contribute a
> modest number of participants (smallish subject pool and 0-2 research
> assistants, tbd).
>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/jodeleeuw/219-2021-eyetracking-
analysis/issues/23#issuecomment-897220533>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/ABOVVYZJV4FMS3QB4SCGOJLT4L7UHANCNFSM5B7ASEBQ>.
Triage notifications on the go with GitHub Mobile for iOS
<https://apps.apple.com/app/apple-store/id1477376905?ct=notification-
email&mt=8&pt=524675> or Android
<https://play.google.com/store/apps/details?id=com.github.android&utm_campaign=notification-
email>.

**Comment by jkhartshorne** [comment]
Rachel is still planning on replicating D. I'm planning on doing A.
