### ISSUE TITLE
Why were these subjects excluded?

### ISSUE THREAD

**Issue by jkhartshorne** [jodeleeuw/219-2021-eyetracking-analysis#25]
Group-E:

`all.data <- all.data %>% filter(subject_id!="603ea6a51c38def3e4140ba6" & subject_id!="5ce1372c55fe0d001869c8d8" & subject_id!="5f47d860b56e68220cb86be1" & subject_id!="607eaf87ac02229ef4fa8f4a" & subject_id!="5d30857eb2f0ad00163470f3" & subject_id!="5e272684f205790453c2c4b8" & subject_id!="5f5b5881b17fa72756b8ff2a" & subject_id!="5fae5291ec402509e2885604")
`

**Comment by jodeleeuw** [comment]
So my notes here are a little vague and I'm going off of what's in the students' write ups, but what I can piece together is that all of these subjects failed the validation check twice. The procedure was to calibrate -> validate -> calibrate again if validation bad -> validate -> continue no matter what. This group decided to exclude all of the subjects who failed the second validation check.
