### ISSUE TITLE
Sample rate question

### ISSUE THREAD

**Issue by jkhartshorne** [jodeleeuw/219-2021-eyetracking-analysis#26]
@jodeleeuw -- is sample rate for data collection determined by jsPsych? WebGazer? The camera? (I mean, there's the sampling rate of the camera, but I mean who decides how often data stamps occur?)

**Comment by jodeleeuw** [comment]
It's... complicated. 

The default WebGazer build attempts to sample every 16.7ms, but in practice it can't compute the predictions this quickly so the CPU becomes the limiting factor. Trying to sample this quickly seems to slow down the overall processing and we were getting sample rates that were sometimes as slow as every 200ms. 

My fork changed this behavior to allow jsPsych to request a sample every X ms, and I think the default we used for these experiments was 34. This seems to work much better. In practice, this can still be CPU limited and the actual sampling rate is variable across participants and within participants.

The data contains an estimate of the sampling rate for each participant in the `trial_type == "webgazer-validate"` trials.
