### ISSUE TITLE
calibration data questions

### ISSUE THREAD

**Issue by jkhartshorne** [jodeleeuw/219-2021-eyetracking-analysis#28]
@raryskin @jodeleeuw @eforbes24 

In looking at group c, I saw that calibration analyses focus on the "boost calibration" phase. Group e doesn't have that phase at all. A very small number of subjects went through "recalibration", but I'm not sure what that means. Was that immediately following the initial calibration if initial calibration wasn't good enough? 

For now, I'm assuming that is the case, so it makes sense to use the second calibration score when there is one.

**Comment by jodeleeuw** [comment]
Yes, "recalibration" was triggered if the initial validation was poor. 

The "boost calibration" was optional, and used by groups with longer experiments. Group C had a particularly weird setup where they calibrated at the start of the experiment and then ran an initial 10 minute task that did not involve eye tracking. Then they used the boost phase to recalibrate right before the main eye tracking task.

I would use the second calibration score when there is one.
