### ISSUE TITLE
Selection of studies

### ISSUE THREAD

**Issue by jkhartshorne** [jodeleeuw/219-2021-eyetracking-analysis#31]
I started some text on how the five studies were selected. Right now, it needs a description of the five studies. It might be nice to include info on number of citations (justifying why these studies and not others).

**Comment by jodeleeuw** [comment]
I've added a table that contains info on topic area, paradigm, and citation count for each study. Since we start each Experiment section with a description of the study I think we can avoid repeating that info here.
