### ISSUE TITLE
Title & author list

### ISSUE THREAD

**Issue by jkhartshorne** [jodeleeuw/219-2021-eyetracking-analysis#32]
Can we please decide a title and authorship list in the next week or two. I don't care what it is, but I do want to be able to cite this in my tenure materials when I submit at the end of the month!

**Comment by jkhartshorne** [comment]
PS I'm cool with what we used for the talk, if we want to take that as a Schelling coordination point :)

**Comment by jodeleeuw** [comment]
Leaving link to the YAML-generating app here for reference:
https://rollercoaster.shinyapps.io/tenzing/
